### ISSUE TITLE
define-component should intern slot accessors into fl.core

### ISSUE THREAD

**Issue by mfiano** [HackerTheory/first-light#22]
psilord: when multiple components export the exact same symbol, it gets annoying when trying to use those components.

**Comment by psilord** [comment]
Yeah, we need to specifically test this situation before figuring out what exactly to do about it, though.  An example is a component like XXX that (:use #:fl.comp.mesh-renderer) and XXX also defines a material slot. Sometimes, things can go weird. We need to identify those things first.
